Search page
kosodrzewina/playlister pull request #12
Opened 2021-08-14 21:42 UTC by kosodrzewina

- replaced home page with search page
- added search functionality
- implemented infinity scrolling (search result)
- now there's an option for adding channel ids
- handling failed requests

2021-08-16 18:16 UTC, shilangyu requested changes

2021-08-16 18:16 UTC, shilangyu commented on lib/widgets/search_field.dart
> +  final Function(String) onSubmitted;
use `ValueChanged<String>` instead

2021-08-16 18:16 UTC, shilangyu commented on lib/widgets/search_field.dart
> +        focusColor: Colors.amber,
Do they look good in light and dark theme?

2021-08-16 18:16 UTC, shilangyu commented on lib/stores/playlist_store.dart
> +      // ignore: avoid_catches_without_on_clauses
Let's remove that lint

2021-08-16 18:16 UTC, shilangyu commented on lib/pages/playlists_page.dart
> +                    item.snippet!.thumbnails.default_?.url ??
Let's create an extension getter for it

2021-08-16 18:16 UTC, shilangyu commented on lib/pages/search_page.dart
> +        ),
Padding instead of Row :)

2021-08-16 18:16 UTC, shilangyu commented on lib/pages/search_page.dart
> +        Row(
looks like a `Center`

2021-08-16 18:16 UTC, shilangyu commented on lib/widgets/search_field.dart
> +  var _currentColor = Colors.white;
Instead of storing currentColor, store `_isFocused` and render the color conditionally

2021-08-16 18:16 UTC, shilangyu commented on lib/widgets/search_list_view.dart
> +    required this.youtubeRepository,
I dont think it has to be passed into this widget

2021-08-16 18:16 UTC, shilangyu commented on lib/widgets/search_list_view.dart
> +    required this.searchPhrase,
This is traditionally called "search term"

2021-08-16 18:16 UTC, shilangyu commented on lib/widgets/search_list_view.dart
> +        ),
Maybe `PlaylistsListItem` could take a model so that it handles the text, thumbnail, and error by itself? Instead of repeating code

2021-08-17 12:37 UTC, kosodrzewina commented on lib/widgets/search_field.dart
> +  final Function(String) onSubmitted;
do you mean only labelText?

2021-08-17 17:08 UTC, shilangyu requested changes

2021-08-17 17:08 UTC, shilangyu commented on lib/widgets/search_field.dart
> +    _focusNode.addListener(() => setState(() => _isFocused = !_isFocused));
This is not necessarely true, it would be better to assign `_isFocused = _focusNode.hasFocus`

2021-08-17 17:08 UTC, shilangyu commented on lib/pages/channel_id_dialog.dart
> +      });
Trailing comma

2021-08-17 17:08 UTC, shilangyu commented on lib/pages/search_page.dart
> +            accentColor: Colors.red,
Was it meant to be hardcoded?

2021-08-17 17:08 UTC, shilangyu commented on lib/pages/search_page.dart
> +                  this.searchTerm = searchTerm.isEmpty ? null : searchTerm);
I think an empty string an null has the same meaning here

2021-08-17 19:15 UTC, shilangyu approved these changes

2021-08-17 19:26 UTC, merged