Handling api key
kosodrzewina/playlister pull request #18
Opened 2021-09-02 18:31 UTC by kosodrzewina

Fixed problems related to an invalid API key (or lack of one):
- if there is no API key search field, channel ID button and remove API key button are disabled
- if user searches with an invalid API key, infinite loading bug does not longer occur

https://user-images.githubusercontent.com/34711852/131897629-c5324444-2436-4684-85a6-b5adff8487fa.mp4

2021-09-04 08:35 UTC, shilangyu requested changes

2021-09-04 08:35 UTC, shilangyu commented on lib/pages/api_key_dialog.dart
> +              icon: context.read<AuthStore>().apiKey != null
Maybe calculate hasApiKey once?

2021-09-04 08:35 UTC, shilangyu commented on lib/widgets/icon_text_button.dart
> +  final Function()? onPressed;
`VoidCallback?` :>

2021-09-04 08:35 UTC, shilangyu commented on lib/pages/search_page.dart
> +                ? () async => await showChannelIdDialog(context)
async/await not needed

2021-09-04 08:35 UTC, shilangyu commented on lib/pages/search_page.dart
> +  void dispose() {
controller also has to be disposed

2021-09-04 08:35 UTC, shilangyu commented on lib/widgets/icon_text_button.dart
> +  final Text text;
I would just make it a `Widget`

2021-09-05 15:07 UTC, shilangyu approved these changes

2021-09-05 15:07 UTC, shilangyu commented on lib/widgets/icon_text_button.dart
> +  final Widget widget;
`text` was ok, but `child` is also ok, `widget` is not ok

2021-09-05 15:07 UTC, shilangyu commented on lib/pages/api_key_dialog.dart
> +            final isApiKey = context.read<AuthStore>().apiKey != null;
`isApiKey` or `hasApiKey`?

2021-09-05 15:10 UTC, kosodrzewina commented on lib/pages/api_key_dialog.dart
> +            final isApiKey = context.read<AuthStore>().apiKey != null;
Why should it be hasApiKey?

2021-09-05 15:29 UTC, merged